version: "3"
services:
  # cos:
  #   image: cos
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - "./config.json:/tmp/centrifugo.json"
  #   links:
  #     - centrifugo
  #     - redis
  redis:
    image: redis
    ports:
    - "6379:6379"
  centrifugo:
    image: centrifugo
    ports:
    - "8000:8000"
    volumes:
    - "./config.json:/tmp/config.json"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
    links:
      - redis